quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

quarkus.rest-client.training-lms.url=http://training-lms-mock:3001
quarkus.rest-client.notification.url=http://notification-mock:3003

teleport.adapter.url=http://teleport-adapter:3500
